### ISSUE TITLE
Differentiate banners between two versions

### ISSUE THREAD

**Issue by Fleker** [ITVlab/TvAppRepo#41]

**Comment by Xstar97** [comment]
umm...can you explain this further?
we cant install the same app with different versions.

**Comment by Fleker** [comment]
There are two package names, one for each version. You should be able to install both on one device.

**Comment by Xstar97** [comment]
for the shortcut & the original app?
or the shortcut's package name will be different based on versions of the app installed?

**Comment by Fleker** [comment]
I'm talking about the TvAppRepo app, differentiating the banner between Community and Play Store versions.

**Comment by Xstar97** [comment]
ohhh...i think you should add a cat(github) to the community banner on 1 of the corners & either a G or play store icon on a corner of the play store banner

**Comment by Fleker** [comment]
Yeah I'll do something along those lines

**Comment by Xstar97** [comment]
I think the play store version should be just the normal banner(because of copyright material ex: google play icon/etc)
However I do believe a cat would be a lovely addition to the community banner since it also pays homage to github too.
but these are just opnions & I do hope you use different banners...I keep launching the wrong one(community crashes on v1.0.4)

**Comment by Fleker** [comment]
New community banner

![banner](https://cloud.githubusercontent.com/assets/3291635/22227007/f238004c-e196-11e6-9fda-7cdc6f9911d4.png)

**Comment by Xstar97** [comment]
awesome!
